/**
 * pages/LandingPage.jsx
 *
 * Public marketing homepage (Phase 3).
 * Non-subscribers land here and are invited to become a founding member.
 * Built strictly from DESIGN.md tokens — warm off-white ground, coral
 * accent, black pill buttons, Satoshi/Newsreader/Plex Mono type system.
 */

import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const NATIONS = [
  { name: 'Kelkelia', color: '#8B4513' },
  { name: 'Corondel', color: '#4169E1' },
  { name: 'Ashen Run', color: '#696969' },
  { name: 'Vantoria', color: '#2E8B57' },
];

const PILLARS = [
  {
    eyebrow: 'Primary',
    title: 'The Archive',
    body:
      'Scrub through 1,950 simulated years. Every nation, region, leader, and population figure is generated by a deterministic simulation engine — not written by hand.',
  },
  {
    eyebrow: 'Included',
    title: 'The Library',
    body:
      'Audio narratives drawn from the same simulated history, for founding members to listen to alongside the data.',
  },
  {
    eyebrow: 'Coming later',
    title: 'The Game',
    body:
      'Asynchronous play inside the simulated world, scoped once the Archive and Library are live for founding members.',
  },
];

function LandingPage() {
  const { user, hasActiveSubscription } = useAuth();

  return (
    <div className="min-h-screen bg-ground">
      {/* ── Nav ─────────────────────────────────────────────────────────── */}


      {/* ── Hero matching Figma Landing - to help with page loading.png ──────── */}
      <section className="w-full bg-[#D9D9D9] py-24 md:py-36 text-center flex flex-col items-center justify-center">
        <h1 className="font-sans font-medium text-4xl sm:text-5xl md:text-6xl tracking-tight text-ink mb-6">
          Shape the future
        </h1>
        <div className="flex justify-center">
          <Link
            to={user ? '/archive' : '/login'}
            className="px-6 py-2 bg-paper border border-rule text-ink font-sans font-medium text-sm rounded hover:bg-paper/80 transition-all shadow-2xs"
          >
            Begin
          </Link>
        </div>
      </section>

      <div className="max-w-content mx-auto px-4 md:px-6">
        {/* Nations strip */}
        <div className="bg-paper rounded-card p-6 border border-rule my-12">
          <p className="font-sans font-medium text-caption tracking-eyebrow uppercase text-ink-muted mb-4">
            Four founding nations, Year 0
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {NATIONS.map((nation) => (
              <div key={nation.name} className="flex items-center gap-2">
                <span
                  className="w-3 h-3 rounded-full flex-shrink-0"
                  style={{ backgroundColor: nation.color }}
                  aria-hidden="true"
                />
                <span className="font-mono text-data text-ink">{nation.name}</span>
              </div>
            ))}
          </div>
        </div>

      {/* ── Pillars ─────────────────────────────────────────────────────── */}
      <section className="pb-16 md:pb-24">
        <h2 className="font-sans font-semibold text-heading text-ink mb-6">
          What founding members get
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {PILLARS.map((pillar) => (
            <div
              key={pillar.title}
              className="bg-paper rounded-card p-8 border border-rule"
            >
              <span className="inline-block bg-neutral-100 text-ink px-3 py-1 rounded-full font-sans font-medium text-small mb-4 border border-rule">
                {pillar.eyebrow}
              </span>
              <h3 className="font-sans font-semibold text-subhead text-ink mb-3">
                {pillar.title}
              </h3>
              <p className="font-serif text-body text-ink-muted">{pillar.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Founding member CTA ─────────────────────────────────────────── */}
      <section className="pb-16 md:pb-24">
        <div className="bg-ink rounded-card p-8 md:p-12 flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div>
            <h2 className="font-sans font-bold text-heading text-paper mb-2">
              £10/month. One tier. Cancel anytime.
            </h2>
            <p className="font-sans text-body text-paper/70">
              Full access to the Archive and Library — no interactive map
              yet, and the Game is still ahead. Just history, honestly
              simulated.
            </p>
          </div>
          <Link
            to={user ? '/pricing' : '/signup'}
            className="px-6 py-3 bg-black text-white border border-neutral-700 font-sans font-semibold text-body rounded-full hover:bg-neutral-800 transition-all duration-hover text-center whitespace-nowrap"
          >
            Join as a Founding Member
          </Link>
        </div>
      </section>
      </div>


    </div>
  );
}

export default LandingPage;
